package blocks

import (
	"os"
	"strings"
	"testing"

	"github.com/BlackMesaLTD/tfreport/internal/core"
)

func loadReport(t *testing.T, path string) *core.Report {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	r, err := core.GenerateReport(data, core.ReportOptions{ChangedOnly: true})
	if err != nil {
		t.Fatal(err)
	}
	return r
}

func fixtureCtx(t *testing.T, target string) *BlockContext {
	t.Helper()
	r := loadReport(t, "../../../testdata/small_plan.json")
	return &BlockContext{
		Target: target,
		Report: r,
		Output: OutputOptions{CodeFormat: "diff", MaxResourcesInSummary: 50},
	}
}

func TestTitle_allTargets(t *testing.T) {
	cases := []struct {
		target   string
		contains string
	}{
		{"markdown", "# Terraform Plan Report"},
		{"github-pr-body", "## Infrastructure Change Summary"},
		{"github-pr-comment", "### Terraform Plan"},
		{"github-step-summary", "Terraform Plan detected changes"},
	}
	for _, c := range cases {
		t.Run(c.target, func(t *testing.T) {
			ctx := fixtureCtx(t, c.target)
			out, err := Title{}.Render(ctx, nil)
			if err != nil {
				t.Fatal(err)
			}
			if !strings.Contains(out, c.contains) {
				t.Errorf("target=%q: %q missing from %q", c.target, c.contains, out)
			}
		})
	}
}

func TestPlanCounts(t *testing.T) {
	ctx := fixtureCtx(t, "github-step-summary")
	out, err := PlanCounts{}.Render(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(out, "Plan:") {
		t.Errorf("want 'Plan:' prefix, got %q", out)
	}
}

func TestKeyChanges_empty(t *testing.T) {
	ctx := &BlockContext{Target: "markdown", Report: &core.Report{}}
	out, err := KeyChanges{}.Render(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	if out != "" {
		t.Errorf("want empty for report with no key changes, got %q", out)
	}
}

func TestKeyChanges_markdownHeader(t *testing.T) {
	ctx := fixtureCtx(t, "markdown")
	out, err := KeyChanges{}.Render(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	// Sample plan has key changes; markdown target should prepend "## Key Changes".
	if len(ctx.Report.KeyChanges) > 0 && !strings.Contains(out, "## Key Changes") {
		t.Errorf("markdown target: want '## Key Changes' header, got %q", out)
	}
}

func TestSummaryTable_module(t *testing.T) {
	ctx := fixtureCtx(t, "markdown")
	out, err := SummaryTable{}.Render(ctx, map[string]any{"group": "module"})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "| Module |") {
		t.Errorf("want Module table header, got %q", out)
	}
}

func TestTextPlan_noBlocks(t *testing.T) {
	ctx := fixtureCtx(t, "github-step-summary")
	// fixture has no text plan blocks populated
	out, err := TextPlan{}.Render(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	if out != "" {
		t.Errorf("want empty with no text plan blocks, got %q", out)
	}
}

func TestInstanceDetail_renders(t *testing.T) {
	ctx := fixtureCtx(t, "github-step-summary")
	out, err := InstanceDetail{}.Render(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	if out == "" {
		t.Error("expected non-empty instance detail")
	}
	if !strings.Contains(out, "<details>") {
		t.Errorf("want <details> in step-summary target, got %q", out)
	}
}

func TestFooter(t *testing.T) {
	ctx := fixtureCtx(t, "github-pr-body")
	out, err := Footer{}.Render(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "Generated by tfreport") {
		t.Errorf("want credit in footer, got %q", out)
	}
}
