package blocks

import (
	"fmt"
	"strings"

	"github.com/BlackMesaLTD/tfreport/internal/core"
)

// Footer renders the closing section. On multi-report renders and on markdown
// target it's a single-line credit; on GitHub targets it also surfaces the
// data-source read count footnote when applicable.
type Footer struct{}

func (Footer) Name() string { return "footer" }

func (Footer) Render(ctx *BlockContext, _ map[string]any) (string, error) {
	var lines []string

	readCount := 0
	for _, r := range allReports(ctx) {
		readCount += r.ActionCounts[core.ActionRead]
	}
	if readCount > 0 {
		lines = append(lines, fmt.Sprintf("<sub>♻️ %d data source reads not shown</sub>", readCount))
	}

	if ctx.Target != "markdown" {
		lines = append(lines, "<sub>Generated by tfreport</sub>")
	}

	return strings.Join(lines, "\n"), nil
}

// Doc describes footer for cmd/docgen.
func (Footer) Doc() BlockDoc {
	return BlockDoc{
		Name:    "footer",
		Summary: "Closing credit line and data-source-read footnote. Target-aware; markdown renders minimal, GitHub targets add the generator credit.",
	}
}

func init() { defaultRegistry.Register(Footer{}) }
