// Command docgen renders the tfreport block reference as Markdown by walking
// the default block registry and calling Block.Doc() on each registered
// block. Output is deterministic (alphabetical by block name; sorted where
// we iterate maps) so `make docs-check` can CI-verify no drift.
//
// Usage:
//
//	go run ./cmd/docgen                        # → stdout
//	go run ./cmd/docgen --out docs/blocks.md   # → file
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/BlackMesaLTD/tfreport/internal/formatter/blocks"
)

func main() {
	out := flag.String("out", "", "write Markdown here instead of stdout")
	flag.Parse()

	doc := renderAll(blocks.Default())

	if *out == "" {
		_, _ = os.Stdout.WriteString(doc)
		return
	}
	if err := os.WriteFile(*out, []byte(doc), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "docgen: %v\n", err)
		os.Exit(1)
	}
}

// renderAll builds the full Markdown document. Sorted block names, sorted
// columns, sorted examples — the output must be byte-identical for identical
// inputs.
func renderAll(reg *blocks.Registry) string {
	names := reg.Names()
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# tfreport Block Reference\n\n")
	b.WriteString("Auto-generated by `cmd/docgen` from the `Block.Doc()` metadata of each registered block. Do not edit by hand; run `make docs` to regenerate.\n\n")
	b.WriteString("See [docs/output-templates.md](output-templates.md) for composition tiers, raw-data escape hatch, and Sprig functions.\n\n")
	b.WriteString("## Blocks\n\n")

	for i, name := range names {
		blk, ok := reg.Get(name)
		if !ok {
			continue
		}
		if i > 0 {
			b.WriteString("\n")
		}
		b.WriteString(renderBlock(blk.Doc()))
	}
	return b.String()
}

// renderBlock produces the Markdown fragment for one block.
func renderBlock(doc blocks.BlockDoc) string {
	var b strings.Builder
	fmt.Fprintf(&b, "### `%s`\n\n", doc.Name)
	if doc.Summary != "" {
		fmt.Fprintf(&b, "%s\n\n", doc.Summary)
	}

	if len(doc.Args) > 0 {
		b.WriteString("**Args:**\n\n")
		b.WriteString("| Name | Type | Default | Description |\n")
		b.WriteString("|------|------|---------|-------------|\n")
		for _, a := range doc.Args {
			fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s |\n",
				a.Name, a.Type, escapeCell(a.Default), escapeCell(a.Description))
		}
		b.WriteString("\n")
	}

	if len(doc.Columns) > 0 {
		// Caller is expected to sort Columns by ID when building Doc(). We
		// re-sort defensively so docgen is deterministic regardless.
		cols := make([]blocks.ColumnDoc, len(doc.Columns))
		copy(cols, doc.Columns)
		sort.Slice(cols, func(i, j int) bool { return cols[i].ID < cols[j].ID })

		b.WriteString("**Columns** (for the `columns` csv arg):\n\n")
		b.WriteString("| ID | Heading | Description |\n")
		b.WriteString("|----|---------|-------------|\n")
		for _, c := range cols {
			if c.Description == "" && c.Heading == "" {
				continue
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n",
				c.ID, escapeCell(c.Heading), escapeCell(c.Description))
		}
		b.WriteString("\n")
	}

	for _, ex := range doc.Examples {
		b.WriteString("**Example:**\n\n")
		fmt.Fprintf(&b, "```tmpl\n%s\n```\n\n", ex.Template)
		if ex.Rendered != "" {
			b.WriteString("Renders:\n\n")
			fmt.Fprintf(&b, "```\n%s\n```\n\n", ex.Rendered)
		}
	}
	return b.String()
}

// escapeCell escapes pipe and newline characters so they don't break the
// Markdown table grammar.
func escapeCell(s string) string {
	if s == "" {
		return "—"
	}
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", `\|`)
	return s
}

